import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Aside from '@/components/aside'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '국립현대미술관',
  description: 'Generated by Hong Yoon Jung',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      {/* <head>
        <link rel="icon" href="/public/favicon.ico" type="image/x-icon" />
      </head> */}
      <body className={inter.className}>
        <Header />
        <Aside />
        {children}
      
      </body>
    </html>
    
  )
}
